services:
  app:
    image: skayfox/exemple
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/app
    command: make test-with-server
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: example
      DATABASE_USERNAME: example
      DATABASE_PASSWORD: example
      DATABASE_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
      caddy:
        condition: service_started
  caddy:
    image: caddy:2
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example"]
      interval: 5s
      timeout: 5s
      retries: 5
